name: Generate ASCII Artwork

on:  
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Checkout Repo Files
        run: ls 

      - name: Executing Shell Script
        run: ./ascii-script.sh
  
