name: First Workflow

on:  
  push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: List and Read files
        run: |
          echo "This is our first GitHub Actions Job"
          ls
          cat README.md
