name: Generate ASCII Artwork

on:  
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
      
      - name: Archive Dragon File
        uses: actions/upload-artifact@v3
        with:
          name: dragon-text-file
          path: dragon.txt
  
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

  docker:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        env:
          CONTAINER_REGISTRY: docker.io
          USERNAME: dockerUsername
        run: echo docker build -t $CONTAINER_REGISTRY/$USERNAME/imageName:latest

      - name: Docker Login
        env:
          USERNAME: dockerUsername
          PASSWORD: s3cUrePaSsw0rd
        run: echo docker login --username=$USERNAME --password=$PASSWORD

      - name: Docker Publish
        env:
          CONTAINER_REGISTRY: docker.io
          USERNAME: dockerUsername
        run: echo docker push $CONTAINER_REGISTRY/$USERNAME/imageName:latest


  deploy:
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo docker run $CONTAINER_REGISTRY/$USERNAME/imageName:latest