name: Concurrency Demo

on: workflow_dispatch

jobs:
    test:
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - name: testing
              run: |
                sleep 6
                echo testing

    deploy:
        needs: test
        timeout-minutes: 1
        concurrency: 
            group: production
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
            - name: deploying
              run: |
                sleep 10
                echo deploying

    docker:
      needs: deploy
      runs-on: ubuntu-latest
        steps:
            - name: deploying
              run: |
                sleep 6
                echo deploying

    docker2:
      needs: docker
      runs-on: ubuntu-latest
        steps:
            - name: deploying
              run: |
                sleep 6
                echo deploying
    docker3:
      needs: test
      runs-on: ubuntu-latest
        steps:
            - name: deploying
              run: |
                sleep 6
                echo deploying
