name: Concurrency Demo

on: workflow_dispatch

jobs:
    test:
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - name: testing
              run: |
                sleep 600
                echo testing

    deploy:
        timeout-minutes: 0.1
        concurrency: 
            group: production
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
            - name: testing
              run: |
                sleep 600
                echo deploying
