name: Deployment - Reusable Workflow

on: 
    workflow_call:
        secrets:
          k8s-kubeconfig:
            description: Secret holding Kubeconfig file
            required: true

jobs:
  dev-deploy:
    outputs:
      APP_INGRESS_URL: ${{ steps.get-ingress-ip-address.outputs.APP_INGRESS_HOST }}
    environment:
      name: development
      url: https://${{ steps.get-ingress-ip-address.outputs.APP_INGRESS_HOST }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0' # default is latest stable
        id: install

      - name: Set Kube Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.k8s-kubeconfig }}
        #  context: <context name>

      - name: Check Kube Nodes
        run: kubectl get nodes

      - name: Nginx Ingress IP
        run: |
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV 

      - name: Replace ENV values
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ env.DOCKERHUB_USERNAME }}/solar-system:${{ env.IMAGE_VERSION }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Check files
        run: |
          cat kubernetes/development/*.yaml
      
      - name: Deploy to K8S Cluster
        run: |
          kubectl apply -f kubernetes/development/
          
      - name: Get IP
        id: get-ingress-ip-address
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
        run: |
          echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ing -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"
