# change this to the event type you want to get the data for
on:
  pull_request:
    types: opened

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  
  commnet:    
    name: ccccccccc event
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt update
        sudo apt install -y jq lolcat fortune boxes
    - name: cccccccccccccc
      run: |
        chmod +x test-script.sh
        ./test-script.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
