name: Solar System

on:  
  workflow_dispatch: 
  push:
    branches: 
      - main
      - '!feature/*'    # ignoring pushing to any feature branch using !

env:
  DOCKERHUB_USERNAME: siddharth67
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  code-coverage:
    container: 
      image: node:19
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup NodeJS Version - 19
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 19

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}    
             
      - name: NPM Install
        run: npm install
      
      - name: NPM Code Coverage
        run: NODE_ENV=deploy npm run coverage
        continue-on-error: true

      - name: Archive Code Coverage Result
        uses: actions/upload-artifact@v3
        with:
          name: Code-Coverage-Result
          path: coverage/

      - name: Code Coverage Annotation
        uses: ggilder/codecoverage@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COVERAGE_FILE_PATH: "./coverage/lcov.info"
          COVERAGE_FORMAT: "lcov"