name: Solar System

on:  
  workflow_dispatch: 
  push:
    branches: 
      - main
      - '!feature/*'    # ignoring pushing to any feature branch using !

jobs:
  unit-testing:
    strategy:
      matrix:
        node_version: [18, 19, 20]
        operating_systems: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating_systems }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS Version - ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
     
      - name: NPM Install
        run: npm install
      
      - name: NPM Testing
        run: NODE_ENV=deploy npm test